---
apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  builders:
    #note that when updating the ref here you must also update kustomization.yaml
    ubi8:
      image: quay.io/sdouglas/hacbs-jdk17-builder:domain
      priority: 2000
    ubi7:
      image: quay.io/redhat-user-workloads/rhtap-build-tenant/jvm-build-service-builder-images/ubi7:d6c417eae5fe32f3207918c6395881843e534a5d
      priority: 1000
