apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-component-build-
spec:
  pipelineRef:
    name: java-builder
    bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
  params:
    - name: git-url
      value: https://github.com/stuartwdouglas/shaded-java-app
    - name: output-image
      value: broken.io/broken:test
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
  serviceAccountNames:
    - serviceAccountName: pipeline
      taskName: build-container
