---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jvm-build-config
data:
  enable-rebuilds: "true"
  maven-repository-300-jboss: "https://repository.jboss.org/nexus/content/groups/public/"
  maven-repository-301-jitpack: "https://jitpack.io"
  maven-repository-302-confluent: "https://packages.confluent.io/maven"
  maven-repository-303-gradle: "https://repo.gradle.org/artifactory/libs-releases"