apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/tektoncd/pipeline/releases/download/v0.34.1/release.yaml
  - https://raw.githubusercontent.com/redhat-appstudio/build-definitions/main/tasks/git-clone.yaml
  - maven-v0.2.yaml
  - rbac.yaml
