apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacbs-jvm-operator
  namespace: jvm-build-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacbs-jvm-operator
  template:
    metadata:
      labels:
        app: hacbs-jvm-operator
    spec:
      containers:
        - name: hacbs-jvm-operator
          image: hacbs-jvm-operator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-metrics
          args:
            - "--zap-log-level=debug"
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      serviceAccountName: hacbs-jvm-operator
