apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

images:
  - name: hacbs-jvm-operator
    newName: quay.io/redhat-appstudio/hacbs-jvm-controller
    newTag: 0225b5510e8f1273b3156a7abf461b211c1e024f
