apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jvm-build-sidecar-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/hacbs-jvm-build-request-processor:{{revision}}'
    - name: path-context
      value: java-components
    - name: dockerfile
      value: build-request-processor/src/main/docker/Dockerfile.all-in-one
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/hacbs-core-service-templates-bundle:latest
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: jvm-build-sidecar-push-{{ revision }}
